# Generated by Django 5.0.2 on 2024-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGroup', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
