# Generated by Django 5.0.2 on 2024-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blood_stock',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
