# Generated by Django 5.0.2 on 2024-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blood_stock_age_blood_stock_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='date_uploaded',
            field=models.DateTimeField(null=True),
        ),
    ]
