# Generated by Django 5.0.3 on 2024-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blood_stock_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='hospital',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
