# Generated by Django 5.0.3 on 2024-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blood_stock_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='hospital_add',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blood_stock',
            name='hospital_num',
            field=models.IntegerField(null=True),
        ),
    ]
