# Generated by Django 5.0.3 on 2024-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blooddonor_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
