# Generated by Django 5.0.3 on 2024-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blood_stock_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='hospital_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
