# Generated by Django 5.0.3 on 2024-03-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_blood_stock_hospital_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_stock',
            name='email',
        ),
    ]
