# Generated by Django 5.0.3 on 2024-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_blood_stock_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor_hospitals',
            name='hos_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blooddonor_organisation',
            name='org_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
