# Generated by Django 5.0.3 on 2024-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blooddonor_hospitals_hos_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
